use std::error::Error as StdError;

// Port https://github.com/Iapetus-11/Villager-Bot/blob/8a36c4e565f4bf5ebcbd19689a3c7357c5f3805b/bot/cogs/core/badges.py#L18

pub async fn generate_user_badges_image() -> Result<String, Box<dyn StdError>> {
    todo!();
}
